export type CodeLang = "java" | "c" | "javascript";

const markerSnippets: Record<string, Partial<Record<CodeLang, Record<string, string>>>> = {
  "Knight's Tour Problem": {
    javascript: {
      "init-board": "board[0][0] = 0;",
      "base-case": "if (move === n * n) return true;",
      "check-move": "if (nx >= 0 && nx < n && ny >= 0 && ny < n && board[nx][ny] === -1) {",
      "place-move": "board[nx][ny] = move;",
      "recurse": "if (solve(nx, ny, move + 1)) return true;",
      "backtrack": "board[nx][ny] = -1;",
      "return-result": "return board.every(row => row.every(cell => cell >= 0)) ? board : null;",
    },
    java: {
      "init-board": "board[0][0] = 0;",
      "base-case": "if (move == n * n) return true;",
      "check-move": "if (nx >= 0 && nx < n && ny >= 0 && ny < n && board[nx][ny] == -1) {",
      "place-move": "board[nx][ny] = move;",
      "recurse": "if (solve(board, nx, ny, move + 1, n)) return true;",
      "backtrack": "board[nx][ny] = -1;",
      "return-result": "return solve(board, 0, 0, 1, n) ? board : null;",
    },
    c: {
      "init-board": "board[0][0] = 0;",
      "base-case": "if (move == N*N) return true;",
      "check-move": "if (nx>=0 && nx<N && ny>=0 && ny<N && board[nx][ny]==-1) {",
      "place-move": "board[nx][ny] = move;",
      "recurse": "if (solve(nx, ny, move+1)) return true;",
      "backtrack": "board[nx][ny] = -1;",
      "return-result": "return solve(0, 0, 1);",
    },
  },
  "N-Queens Problem": {
    javascript: {
      "base-case": "if (col >= n) return true;",
      "check-safe": "if (isSafe(i, col)) {",
      "place-queen": "board[i][col] = 1;",
      "recurse": "if (solve(col+1)) return true;",
      "backtrack": "board[i][col] = 0;",
      "return-result": "return board;",
    },
    java: {
      "base-case": "if (col >= n) return true;",
      "check-safe": "if (isSafe(board, i, col, n)) {",
      "place-queen": "board[i][col] = 1;",
      "recurse": "if (solve(board, col+1, n)) return true;",
      "backtrack": "board[i][col] = 0;",
    },
    c: {
      "base-case": "if (col >= N) return true;",
      "check-safe": "if (isSafe(i, col)) {",
      "place-queen": "board[i][col] = 1;",
      "recurse": "if (solve(col+1)) return true;",
      "backtrack": "board[i][col] = 0;",
    },
  },
  "Hamiltonian Cycles": {
    javascript: {
      "init-path": "path[0] = 0;",
      "check-cycle": "if (pos === V) return !!graph[path[pos-1]][path[0]];",
      "check-move": "if (isSafe(v, pos)) {",
      "place-node": "path[pos] = v;",
      "recurse": "if (solve(pos + 1)) return true;",
      "backtrack": "path[pos] = -1;",
      "return-result": "return solve(1) ? path : null;",
    },
    java: {
      "check-cycle": "if (pos == V) return graph[path[pos - 1]][path[0]] == 1;",
      "check-move": "if (isSafe(v, graph, path, pos)) {",
      "place-node": "path[pos] = v;",
      "recurse": "if (solve(graph, path, pos + 1)) return true;",
      "backtrack": "path[pos] = -1;",
      "init-path": "path[0] = 0;",
      "return-result": "return solve(graph, path, 1) ? path : null;",
    },
    c: {
      "check-cycle": "if (pos == V) return graph[path[pos-1]][path[0]] == 1;",
      "check-move": "if (isSafe(v, graph, pos)) {",
      "place-node": "path[pos] = v;",
      "recurse": "if (solve(graph, pos + 1)) return true;",
      "backtrack": "path[pos] = -1;",
      "init-path": "path[0] = 0;",
      "return-result": "return solve(graph, 1);",
    },
  },
  "Sum of Subsets": {
    javascript: {
      "check-found": "if (sum === target) { results.push([...current]); return; }",
      "check-bounds": "if (idx >= set.length || sum > target) return;",
      "include-item": "current.push(set[idx]);",
      "recurse-include": "solve(idx + 1, current, sum + set[idx]);",
      "backtrack-item": "current.pop();",
      "recurse-exclude": "solve(idx + 1, current, sum);",
      "init-search": "solve(0, [], 0);",
      "return-result": "return results;",
    },
    java: {
      "check-found": "if (sum == 0) { printSubset(set, include); return; }",
      "check-bounds": "if (idx >= n || sum < 0) return;",
      "include-item": "include[idx] = true;",
      "recurse-include": "solve(set, n, sum - set[idx], idx + 1, include);",
      "backtrack-item": "include[idx] = false;",
      "recurse-exclude": "solve(set, n, sum, idx + 1, include);",
    },
    c: {
      "check-found": "if (sum == 0) { printSubset(set, include, n); return; }",
      "check-bounds": "if (idx >= n || sum < 0) return;",
      "include-item": "include[idx] = 1;",
      "recurse-include": "solve(set, n, sum - set[idx], idx + 1, include);",
      "backtrack-item": "include[idx] = 0;",
      "recurse-exclude": "solve(set, n, sum, idx + 1, include);",
    },
  },
  "Binary Search": {
    javascript: {
      "init-bounds": "let lo = 0, hi = arr.length - 1;",
      "check-loop": "while (lo <= hi) {",
      "compute-mid": "const mid = Math.floor((lo + hi) / 2);",
      "check-found": "if (arr[mid] === target) return mid;",
      "move-right": "if (arr[mid] < target) lo = mid + 1;",
      "move-left": "else hi = mid - 1;",
      "return-missing": "return -1;",
    },
    java: {
      "init-bounds": "int lo = 0, hi = arr.length - 1;",
      "check-loop": "while (lo <= hi) {",
      "compute-mid": "int mid = lo + (hi - lo) / 2;",
      "check-found": "if (arr[mid] == target) return mid;",
      "move-right": "if (arr[mid] < target) lo = mid + 1;",
      "move-left": "else hi = mid - 1;",
      "return-missing": "return -1;",
    },
    c: {
      "init-bounds": "int lo = 0, hi = n - 1;",
      "check-loop": "while (lo <= hi) {",
      "compute-mid": "int mid = lo + (hi - lo) / 2;",
      "check-found": "if (arr[mid] == target) return mid;",
      "move-right": "if (arr[mid] < target) lo = mid + 1;",
      "move-left": "else hi = mid - 1;",
      "return-missing": "return -1;",
    },
  },
  "Breadth-First Search": {
    javascript: {
      "init-queue": "const visited = new Set([start]);",
      "dequeue-node": "const node = queue.shift();",
      "check-neighbor": "for (const nb of adjList[node])",
      "visit-neighbor": "if (!visited.has(nb)) { visited.add(nb); queue.push(nb); }",
      "enqueue-neighbor": "if (!visited.has(nb)) { visited.add(nb); queue.push(nb); }",
      "return-order": "return order;",
    },
    java: {
      "init-queue": "visited[start] = true; queue.add(start);",
      "dequeue-node": "int node = queue.poll();",
      "check-neighbor": "for (int nb : adj.get(node))",
      "visit-neighbor": "if (!visited[nb]) { visited[nb] = true; queue.add(nb); }",
      "enqueue-neighbor": "if (!visited[nb]) { visited[nb] = true; queue.add(nb); }",
    },
    c: {
      "init-queue": "visited[start] = true; queue[rear++] = start;",
      "dequeue-node": "int node = queue[front++];",
      "check-neighbor": "if (adj[node][i] && !visited[i]) { visited[i]=true; queue[rear++]=i; }",
      "visit-neighbor": "if (adj[node][i] && !visited[i]) { visited[i]=true; queue[rear++]=i; }",
      "enqueue-neighbor": "if (adj[node][i] && !visited[i]) { visited[i]=true; queue[rear++]=i; }",
    },
  },
  "Depth-First Search": {
    javascript: {
      "init-stack": "const stack = [start];",
      "pop-node": "const node = stack.pop();",
      "mark-visited": "visited.add(node);",
      "check-neighbor": "for (const nb of adj[node])",
      "push-neighbor": "if (!visited.has(nb)) stack.push(nb);",
      "return-visited": "return visited;",
    },
    java: {
      "init-stack": "Stack<Integer> stack = new Stack<>();",
      "pop-node": "int node = stack.pop();",
      "mark-visited": "visited[node] = true;",
      "check-neighbor": "for (int nb : adj.get(node))",
      "push-neighbor": "if (!visited[nb]) stack.push(nb);",
      "return-visited": "return visited;",
    },
    c: {
      "init-stack": "stack[++top] = start;",
      "pop-node": "int node = stack[top--];",
      "mark-visited": "visited[node] = true;",
      "check-neighbor": "if (adj[node][i] && !visited[i])",
      "push-neighbor": "stack[++top] = i;",
      "return-visited": "}",
    },
  },
  "Flood Fill": {
    javascript: {
      "check-bounds": "if (i < 0 || i >= G.length || j < 0 || j >= G[i].length) return;",
      "check-color": "if (G[i][j] !== oldColor) return;",
      "fill-cell": "G[i][j] = newColor;",
      "recurse-neighbor": "FloodFill(i + 1, j, oldColor, newColor);",
      "return-result": "FloodFill(4, 4, '-', 'a');",
    },
    java: {
      "check-bounds": "if (r < 0 || r >= image.length || c < 0 || c >= image[0].length) return;",
      "check-color": "if (image[r][c] != oldColor) return;",
      "fill-cell": "image[r][c] = newColor;",
      "recurse-neighbor": "fill(image, r + 1, c, oldColor, newColor);",
      "return-result": "fill(image, sr, sc, oldColor, newColor);",
    },
    c: {
      "check-bounds": "if (x < 0 || x >= rows || y < 0 || y >= cols) return;",
      "check-color": "if (screen[x][y] != prevC) return;",
      "fill-cell": "screen[x][y] = newC;",
      "recurse-neighbor": "floodFill(screen, x + 1, y, prevC, newC);",
      "return-result": "}",
    },
  },
  "Bubble Sort": {
    javascript: {
      "init-length": "let N = D.length;",
      "start-pass": "do {",
      "compare-pair": "if (D[i - 1] > D[i]) {",
      "swap-pair": "D[i - 1] = D[i];",
      "end-pass": "} while (swapped);",
      "return-sorted": "} while (swapped);",
    },
    java: {
      "init-length": "int n = arr.length;",
      "start-pass": "for (int i = 0; i < n - 1; i++) {",
      "compare-pair": "if (arr[j] > arr[j + 1]) {",
      "swap-pair": "int temp = arr[j];",
      "end-pass": "}",
      "return-sorted": "return arr;",
    },
    c: {
      "init-length": "int n = sizeof(arr) / sizeof(arr[0]);",
      "start-pass": "for (int i = 0; i < n - 1; i++) {",
      "compare-pair": "if (arr[j] > arr[j + 1]) {",
      "swap-pair": "int temp = arr[j];",
      "end-pass": "}",
      "return-sorted": "}",
    },
  },
  "Comb Sort": {
    javascript: {
      "init-gap": "let gap = n;",
      "shrink-gap": "gap = Math.max(1, Math.floor(gap / 1.3));",
      "compare-gap": "if (a[i] > a[i + gap]) {",
      "swap-gap": "[a[i], a[i + gap]] = [a[i + gap], a[i]];",
      "end-pass": "if (steps.length > 500) break;",
      "return-sorted": "return steps;",
    },
    java: {
      "init-gap": "int gap = n;",
      "shrink-gap": "gap = Math.max(1, (int)(gap / 1.3));",
      "compare-gap": "if (arr[i] > arr[i + gap]) {",
      "swap-gap": "int temp = arr[i];",
      "end-pass": "}",
      "return-sorted": "return arr;",
    },
    c: {
      "init-gap": "int gap = n;",
      "shrink-gap": "gap = gap / 1.3;",
      "compare-gap": "if (arr[i] > arr[i + gap]) {",
      "swap-gap": "int temp = arr[i];",
      "end-pass": "}",
      "return-sorted": "}",
    },
  },
  "Cycle Sort": {
    javascript: {
      "init-cycle": "for (let cs = 0; cs < n - 1; cs++) {",
      "start-cycle": "let item = a[cs];",
      "find-position": "if (a[i] < item) pos++;",
      "skip-cycle": "if (pos === cs) continue;",
      "write-item": "[a[pos], item] = [item, a[pos]];",
      "rotate-cycle": "while (pos !== cs) {",
      "return-sorted": "return steps;",
    },
    java: {
      "init-cycle": "for (int cycleStart = 0; cycleStart <= n - 2; cycleStart++) {",
      "start-cycle": "int item = arr[cycleStart];",
      "find-position": "if (arr[i] < item) pos++;",
      "skip-cycle": "if (pos == cycleStart) continue;",
      "write-item": "int temp = item;",
      "rotate-cycle": "while (pos != cycleStart) {",
      "return-sorted": "return arr;",
    },
    c: {
      "init-cycle": "for (int cycleStart = 0; cycleStart <= n - 2; cycleStart++) {",
      "start-cycle": "item = arr[cycleStart];",
      "find-position": "if (arr[i] < item) pos++;",
      "skip-cycle": "if (pos == cycleStart) continue;",
      "write-item": "temp = arr[pos];",
      "rotate-cycle": "while (pos != cycleStart) {",
      "return-sorted": "}",
    },
  },
  "Heapsort": {
    javascript: {
      "init-length": "const a = [...arr], n = a.length;",
      "build-heap": "for (let i = Math.floor(n/2)-1; i >= 0; i--) heapify(n, i);",
      "compare-child": "if (l < size && a[l] > a[largest]) largest = l;",
      "swap-root": "[a[i], a[largest]] = [a[largest], a[i]];",
      "extract-max": "for (let i = n-1; i > 0; i--) {",
      "heapify-down": "heapify(i, 0);",
      "return-sorted": "return a;",
    },
    java: {
      "init-length": "int n = arr.length;",
      "build-heap": "for (int i = n / 2 - 1; i >= 0; i--) heapify(arr, n, i);",
      "compare-child": "if (l < n && arr[l] > arr[largest]) largest = l;",
      "swap-root": "int t = arr[i]; arr[i] = arr[largest]; arr[largest] = t;",
      "extract-max": "int t = arr[0]; arr[0] = arr[i]; arr[i] = t;",
      "heapify-down": "heapify(arr, i, 0);",
      "return-sorted": "}",
    },
    c: {
      "init-length": "void heapSort(int arr[], int n) {",
      "build-heap": "for (int i = n / 2 - 1; i >= 0; i--) heapify(arr, n, i);",
      "compare-child": "if (l < n && arr[l] > arr[largest]) largest = l;",
      "swap-root": "int t=arr[i]; arr[i]=arr[largest]; arr[largest]=t;",
      "extract-max": "int t=arr[0]; arr[0]=arr[i]; arr[i]=t;",
      "heapify-down": "heapify(arr, i, 0);",
      "return-sorted": "}",
    },
  },
  "Bridge Finding": {
    javascript: {
      "visit-node": "disc[u] = low[u] = timer++;",
      "tree-edge": "if (disc[v] === -1) {",
      "back-edge": "} else if (v !== parent) {",
      "update-low": "low[u] = Math.min(low[u], low[v]);",
      "bridge-found": "if (low[v] > disc[u])",
      "return-result": "return bridges;",
    },
    java: {
      "visit-node": "vis[u] = true; disc[u] = low[u] = timer++;",
      "tree-edge": "if (!vis[v]) {",
      "back-edge": "else if (v != parent)",
      "update-low": "low[u] = Math.min(low[u], low[v]);",
      "bridge-found": "if (low[v] > disc[u])",
    },
    c: {
      "visit-node": "vis[u] = true; disc[u] = low[u] = timer++;",
      "tree-edge": "if (!vis[v]) {",
      "back-edge": "else if (v != parent && disc[v] < low[u])",
      "update-low": "if (low[v] < low[u]) low[u] = low[v];",
      "bridge-found": "if (low[v] > disc[u]) printf(\"Bridge: %d-%d\\n\", u, v);",
    },
  },
  "Binary Search Tree": {
    javascript: {
      "choose-direction": "if (val < this.val)",
      "insert-left": "this.left ? this.left.insert(val) : (this.left = new BST(val));",
      "insert-right": "this.right ? this.right.insert(val) : (this.right = new BST(val));",
      "search-found": "if (this.val === val) return this;",
      "search-left": "if (val < this.val) return this.left?.search(val) ?? null;",
      "search-right": "return this.right?.search(val) ?? null;",
    },
    java: {
      "insert-root": "if (root == null) return new BST(val);",
      "choose-direction": "if (val < root.val) root.left = insert(root.left, val);",
      "insert-right": "else root.right = insert(root.right, val);",
      "search-found": "if (root == null || root.val == val) return root;",
      "search-left": "return val < root.val ? search(root.left, val) : search(root.right, val);",
    },
    c: {
      "insert-root": "if (!root) return newNode(val);",
      "choose-direction": "if (val < root->val) root->left = insert(root->left, val);",
      "insert-right": "else root->right = insert(root->right, val);",
    },
  },
  "Depth-Limited Search": {
    javascript: {
      "check-target": "if (node === target) return true;",
      "check-limit": "if (depth >= limit) return false;",
      "mark-visited": "visited.add(node);",
      "recurse": "if (!visited.has(next) && dls(next, depth + 1)) return true;",
      "return-false": "return false;",
    },
    java: {
      "check-target": "if (node == target) return true;",
      "check-limit": "if (limit <= 0) return false;",
      "mark-visited": "visited[node] = true;",
      "recurse": "if (!visited[next] && dls(next, target, limit-1, adj, visited))",
      "return-false": "return false;",
    },
    c: {
      "check-target": "if (node == target) return true;",
      "check-limit": "if (limit <= 0) return false;",
      "mark-visited": "visited[node] = true;",
      "recurse": "if (adj[node][i] && !visited[i] && dls(i, target, limit-1, adj, n, visited))",
      "return-false": "return false;",
    },
  },
  "Topological Sort": {
    javascript: {
      "count-indegree": "if (G[currNode][currNodeNeighbor]) {",
      "increment-indegree": "inDegrees[currNodeNeighbor]++;",
      "enqueue-zero": "Q.push(node);",
      "check-queue": "while (Q.length > 0) {",
      "shift-queue": "const currNode = Q.shift();",
      "decrement-indegree": "inDegrees[i]--;",
      "enqueue-neighbor": "Q.push(i);",
    },
    java: {
      "count-indegree": "for (int v : neighbors) indegree[v]++;",
      "enqueue-zero": "if (indegree[i] == 0) q.add(i);",
      "check-queue": "while (!q.isEmpty()) {",
      "shift-queue": "int u = q.poll();",
      "decrement-indegree": "if (--indegree[v] == 0) q.add(v);",
    },
    c: {
      "count-indegree": "if (adj[i][j]) indegree[j]++;",
      "enqueue-zero": "if (indegree[i] == 0) queue[rear++] = i;",
      "check-queue": "while (front < rear) {",
      "shift-queue": "int u = queue[front++];",
      "decrement-indegree": "if (--indegree[v] == 0) queue[rear++] = v;",
    },
  },
  "Binary Tree Traversal": {
    javascript: {
      "check-null": "if (root == -1) {",
      "traverse-left": "inOrder(T[root][0], root);",
      "visit-node": "printOrder[index++] = root;",
      "traverse-right": "inOrder(T[root][1], root);",
    },
    java: {
      "check-null": "if (root == null) return;",
      "traverse-left": "inorder(root.left);",
      "visit-node": "System.out.print(root.val + \" \");",
      "traverse-right": "inorder(root.right);",
    },
    c: {
      "check-null": "if (!root) return;",
      "traverse-left": "inorder(root->left);",
      "visit-node": "printf(\"%d \", root->val);",
      "traverse-right": "inorder(root->right);",
    },
  },
  "Bipartiteness Test": {
    javascript: {
      "init-colors": "const color = Array(V).fill(-1);",
      "color-start": "const queue = [0]; color[0] = 0;",
      "dequeue-node": "const u = queue.shift();",
      "check-neighbor": "for (const v of adj[u]) {",
      "color-neighbor": "if (color[v] === -1) { color[v] = 1-color[u]; queue.push(v); }",
      "enqueue-neighbor": "if (color[v] === -1) { color[v] = 1-color[u]; queue.push(v); }",
      "detect-conflict": "else if (color[v] === color[u]) return false;",
      "return-true": "return true;",
    },
    java: {
      "init-colors": "Arrays.fill(color, -1);",
      "color-start": "color[0] = 0; q.add(0);",
      "dequeue-node": "int u = q.poll();",
      "check-neighbor": "if (adj[u][v] == 1) {",
      "color-neighbor": "if (color[v] == -1) { color[v] = 1-color[u]; q.add(v); }",
      "enqueue-neighbor": "if (color[v] == -1) { color[v] = 1-color[u]; q.add(v); }",
      "detect-conflict": "else if (color[v] == color[u]) return false;",
      "return-true": "return true;",
    },
    c: {
      "init-colors": "int color[MAX]; memset(color, -1, sizeof(color));",
      "color-start": "color[0] = 0; queue[rear++] = 0;",
      "dequeue-node": "int u = queue[front++];",
      "check-neighbor": "if (adj[u][v]) {",
      "color-neighbor": "if (color[v]==-1) { color[v]=1-color[u]; queue[rear++]=v; }",
      "enqueue-neighbor": "if (color[v]==-1) { color[v]=1-color[u]; queue[rear++]=v; }",
      "detect-conflict": "else if (color[v]==color[u]) return false;",
      "return-true": "return true;",
    },
  },
};

const markerMessages: Record<string, Record<string, string>> = {
  "Knight's Tour Problem": {
    "init-board": "Initialized the board and placed the knight at the starting square.",
    "base-case": "All squares have been visited. The tour is complete.",
    "check-move": "Checking whether the next knight move is valid and unvisited.",
    "place-move": "Placed the knight on the chosen next square.",
    "recurse": "Recursing to continue the tour from the new position.",
    "backtrack": "Dead end reached. Backtracking to try another move.",
    "return-result": "Returning the final Knight's Tour board.",
  },
  "N-Queens Problem": {
    "base-case": "All columns are filled. A valid queen placement was found.",
    "check-safe": "Testing whether the current row is safe for the queen.",
    "place-queen": "Placed a queen on the board.",
    "recurse": "Moving to the next column to place the next queen.",
    "backtrack": "Conflict later on. Removing the queen and trying another row.",
    "return-result": "Returning the completed N-Queens board.",
  },
  "Hamiltonian Cycles": {
    "init-path": "Started the path from the first vertex.",
    "check-cycle": "Checking whether the path closes back to the start vertex.",
    "check-move": "Testing whether the next vertex is safe to add to the path.",
    "place-node": "Added a vertex to the current Hamiltonian path.",
    "recurse": "Continuing the search from the newly added vertex.",
    "backtrack": "This branch failed. Backtracking to try a different vertex.",
    "return-result": "Returning the Hamiltonian cycle result.",
  },
  "Sum of Subsets": {
    "check-found": "Checking whether the current subset already matches the target sum.",
    "check-bounds": "Stopping this branch because we ran out of items or exceeded the target.",
    "include-item": "Including the current value in the subset.",
    "recurse-include": "Exploring the branch where the current value is included.",
    "backtrack-item": "Removing the current value to try the next branch.",
    "recurse-exclude": "Exploring the branch where the current value is excluded.",
    "init-search": "Starting the subset search from index 0.",
    "return-result": "Returning all matching subsets.",
  },
  "Binary Search": {
    "init-bounds": "Initialized the low and high bounds for the search.",
    "check-loop": "Checking whether the current search range is still valid.",
    "compute-mid": "Computing the middle index of the active range.",
    "check-found": "Comparing the middle value with the target.",
    "move-right": "Target is larger, so the search moves to the right half.",
    "move-left": "Target is smaller, so the search moves to the left half.",
    "return-missing": "Target was not found in the array.",
  },
  "Breadth-First Search": {
    "init-queue": "Initializing the BFS queue with the starting node.",
    "dequeue-node": "Removing the next node from the queue.",
    "check-neighbor": "Inspecting a neighboring node from the current node.",
    "visit-neighbor": "Marking a newly discovered neighbor as visited.",
    "enqueue-neighbor": "Adding the discovered neighbor to the queue.",
    "return-order": "Breadth-first traversal is complete.",
  },
  "Depth-First Search": {
    "init-stack": "Initializing the DFS stack with the starting node.",
    "pop-node": "Removing the next node from the DFS stack.",
    "mark-visited": "Marking the current node as visited.",
    "check-neighbor": "Inspecting a neighbor of the current node.",
    "push-neighbor": "Pushing an unvisited neighbor onto the DFS stack.",
    "return-visited": "Depth-first traversal is complete.",
  },
  "Flood Fill": {
    "check-bounds": "Checking whether the current cell is inside the grid.",
    "check-color": "Checking whether the current cell still has the old color.",
    "fill-cell": "Filling the current cell with the new color.",
    "recurse-neighbor": "Recursing into the four neighboring cells.",
    "return-result": "Flood fill is complete.",
  },
  "Bubble Sort": {
    "init-length": "Initializing the array length before sorting starts.",
    "start-pass": "Starting a new Bubble Sort pass over the array.",
    "compare-pair": "Comparing two adjacent elements.",
    "swap-pair": "Swapping the adjacent elements because they are out of order.",
    "end-pass": "The current pass is complete.",
    "return-sorted": "Bubble Sort is complete.",
  },
  "Comb Sort": {
    "init-gap": "Initializing the comb gap before sorting begins.",
    "shrink-gap": "Shrinking the current comb gap.",
    "compare-gap": "Comparing two elements separated by the current gap.",
    "swap-gap": "Swapping out-of-order elements for the current gap.",
    "end-pass": "The current comb pass is complete.",
    "return-sorted": "Comb Sort is complete.",
  },
  "Cycle Sort": {
    "init-cycle": "Starting the outer Cycle Sort loop.",
    "start-cycle": "Taking the current item as the start of a cycle.",
    "find-position": "Counting how many items belong before the current item.",
    "skip-cycle": "Skipping this cycle because the item is already in the correct spot.",
    "write-item": "Writing the item into its computed position.",
    "rotate-cycle": "Rotating the remaining items in the current cycle.",
    "return-sorted": "Cycle Sort is complete.",
  },
  "Heapsort": {
    "init-length": "Initializing the array length before heap operations.",
    "build-heap": "Building the initial max heap.",
    "compare-child": "Comparing the current node with one of its children.",
    "swap-root": "Swapping the node with the larger child to fix the heap.",
    "extract-max": "Moving the heap max to the next position in the sorted suffix.",
    "heapify-down": "Restoring the heap property on the smaller prefix.",
    "return-sorted": "Heapsort is complete.",
  },
  "Bridge Finding": {
    "visit-node": "Visiting a node and assigning its discovery and low-link values.",
    "tree-edge": "Following an unvisited edge deeper into DFS.",
    "back-edge": "Using a back edge to update the current low-link value.",
    "update-low": "Propagating a child's low-link value back to its parent.",
    "bridge-found": "This edge is a bridge because the child cannot reach an earlier ancestor.",
    "return-result": "Bridge search is complete.",
  },
  "Binary Search Tree": {
    "insert-root": "Inserted the first value as the root of the tree.",
    "choose-direction": "Comparing the current value to decide whether to go left or right.",
    "insert-left": "Inserted the value into the left branch.",
    "insert-right": "Inserted the value into the right branch.",
    "search-found": "Checking whether the current tree node matches the target.",
    "search-left": "Target is smaller, so the search moves to the left subtree.",
    "search-right": "Target is larger, so the search moves to the right subtree.",
  },
  "Depth-Limited Search": {
    "check-target": "Checking whether the current node is the target.",
    "check-limit": "Checking whether the depth limit has been reached.",
    "mark-visited": "Marking the current node as visited.",
    "recurse": "Exploring the next child within the remaining depth limit.",
    "return-false": "No valid path was found from this branch.",
  },
  "Topological Sort": {
    "count-indegree": "Scanning edges to compute in-degrees for each node.",
    "increment-indegree": "Incrementing the in-degree of a neighbor node.",
    "enqueue-zero": "Adding a zero in-degree node to the queue.",
    "check-queue": "Checking whether there are still nodes left to process.",
    "shift-queue": "Removing the next available node from the queue.",
    "decrement-indegree": "Removing an incoming edge and updating in-degree.",
    "enqueue-neighbor": "A neighbor reached zero in-degree and is enqueued.",
  },
  "Binary Tree Traversal": {
    "check-null": "Checking whether the current node exists before traversing further.",
    "traverse-left": "Traversing into the left subtree.",
    "visit-node": "Visiting the current node and adding it to the traversal output.",
    "traverse-right": "Traversing into the right subtree.",
  },
  "Bipartiteness Test": {
    "init-colors": "Initializing all graph nodes as uncolored.",
    "color-start": "Coloring the start node and seeding the BFS queue.",
    "dequeue-node": "Removing the next node from the BFS queue.",
    "check-neighbor": "Checking the current edge to inspect a neighbor.",
    "color-neighbor": "Assigning the opposite color to an uncolored neighbor.",
    "enqueue-neighbor": "Adding the newly colored neighbor to the queue.",
    "detect-conflict": "Two adjacent nodes share the same color, so the graph is not bipartite.",
    "return-true": "All reachable edges satisfy the two-coloring rule.",
  },
};

export function getActiveCodeLine(
  algorithmName: string,
  lang: CodeLang,
  marker: string | null,
  code: string,
): number | null {
  if (!marker) return null;

  const snippet = markerSnippets[algorithmName]?.[lang]?.[marker];
  if (!snippet) return null;

  const lines = code.split("\n");
  const index = lines.findIndex((line) => line.includes(snippet));
  return index >= 0 ? index + 1 : null;
}

export function getStepMessage(algorithmName: string, marker: string | null): string | null {
  if (!marker) return null;
  return markerMessages[algorithmName]?.[marker] ?? null;
}
